### ISSUE TITLE
[S5148F-ON] UNKNOWN: Unable to get SNMP metrics for temp mode

### ISSUE THREAD

**Issue by lboue** [eric-belhomme/nagios_check_dell_s_series#1]
Hello,

I am facing an issue when I execute you Python script and call the temp mode. My device is an **DELL EMC S5148F-ON** running 10.4.1.0. Here is the CLI output:

```
OS10# show version 
Dell EMC Networking OS10-Enterprise
Copyright (c) 1999-2018 by Dell Inc. All Rights Reserved.
OS Version: 10.4.1.0
Build Version: 10.4.1.0.483
Build Time: 2018-07-27T09:26:42-0700
System Type: S5148F-ON
Architecture: x86_64
```
 **fans and power check -> OK**
It works fine for fans and power check but fails for temp 

```
[user@host libexec]$ ./check_dell_s_series.py -H 172.16.1.254 -C ************ -m fans
OK : all fan(s) OK
fan number 1 reported as up
fan number 2 reported as up
fan number 3 reported as up
fan number 4 reported as up
```

```
[user@host libexec]$ ./check_dell_s_series.py -H 172.16.1.254 -C ************ -m power
OK : all PSU(s) OK
PSU number 1 reported as up
PSU number 2 reported as up
```

 **temp and healthcheck -> KO**
```
[user@host libexec]$ ./check_dell_s_series.py -H 172.16.1.254 -C ************ -m temp
UNKNOWN: Unable to get SNMP metrics from server !
```

```
[user@host libexec]$ ./check_dell_s_series.py -H 172.16.1.254 -C ************ -m health
Traceback (most recent call last):
  File "./check_dell_s_series.py", line 277, in <module>
    retCode = getSystemInfo()
  File "./check_dell_s_series.py", line 139, in getSystemInfo
    message.append('chassis: ' + Os10ChassisDefType.get(vals[0]) + ' (rev. ' + vals[1] + ') - p/n:' + vals[2] + ' - ServiceTag:' + vals[3])
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Can I do some debugs to find what is wrong?
I don't understand what is wrong because I am getting a respond with the CLI command:

**Tests**
```
[user@host tmp]$ snmpwalk -Cc 172.16.1.254 -c ************-v 2c .1.3.6.1.4.1.674.11000.5000.100.4.1.1.3.1.11
SNMPv2-SMI::enterprises.674.11000.5000.100.4.1.1.3.1.11.1 = INTEGER: 44
```

Regards,
Ludovic

**Comment by lboue** [comment]
It seems working with the following code:

```
def getTemperatures(warn, crit):
    retCode = 0
    message = []
    vars = netsnmp.VarList(
        #netsnmp.Varbind('.1.3.6.1.4.1.674.11000.5000.100.4.1.1.3.1.11'), # chassis temp.
        #netsnmp.Varbind('.1.3.6.1.4.1.674.11000.5000.100.4.1.1.4.1.5'))  # card temp.
        netsnmp.Varbind('.1.3.6.1.4.1.674.11000.5000.100.4.1.1.3.1.11.1'), # chassis temp.
        netsnmp.Varbind('.1.3.6.1.4.1.674.11000.5000.100.4.1.1.4.1.5.1.1'))  # card temp.
    #vals = snmpSession.walk(vars) # doesn't work with walk mode
    vals = snmpSession.get(vars)
    ....
```

**Comment by eric-belhomme** [comment]
Hello Ludovic,
Sorry for the delayed answer... I just missed your report !
BTW, I branched your patch, I'll merge it as soon as I'll verify that it doesn't introduce any regression on my own switches :)

Regards,

Eric

**Comment by lboue** [comment]
Thanks for your response. I hope it will be OK.
